spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource :
 #   url : jdbc:postgresql://localhost:5432/AWS_TEST
  #  username: postgres
   # password: 3621
    url : jdbc:postgresql://smrp.csz0y3ch3vk9.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: wnstlr0615
    password: Wlwns135
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql

    hibernate:
      ddl-auto: update
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test